### PR TITLE
Added option to start hidden

### PR DESCRIPTION
**Pull request by aadfPT**
Modified the application as to have a new setting that allows it to start hidden.

### CODE REVIEW

**Comment by ArcadeRenegade** [comment]
Thanks but I'm confused as to why the user wants the sidebar to be initially hidden when it starts up?

**Comment by aadfPT** [comment]
I personally like to have it hidden, and toggle it visible when I want a
quick glance at the data.

**Comment by ArcadeRenegade** [comment]
I added this feature but I implemented my own version.

**Comment by aadfPT** [comment]
Thank you.

**Pull request closed without merging**
