### PR TITLE
.Net Core port

### PR DESCRIPTION
**Pull request by ThaChillera**
This is a port of the project to .Net Core. 

This is the first step to solving #255, and a preparation to Microsoft deprecating .net Framework.
Things done:
- Merged packages.json and .csproj into the new .csproj format
- Removed OpenHardwareMonitor Submodule (unused)
- Updated LibreHardwareMonitor to latest commit (so it supports .Net Core)
- Added LibreHardwareMonitor as subproject to .sln (so its included in the build, manually linking the .DLL causes it to miss dependencies)

### CODE REVIEW

**Comment by ThaChillera** [comment]
Testing & feedback is very welcome

**Comment by ArcadeRenegade** [comment]
Thank you for this. This is really cool. I'll take a look tomorrow when I have time.

By the way I haven't had much time to keep up with this project. Would you like to be added as an owner?

**Comment by ixuz** [comment]
> Thank you for this. This is really cool. I'll take a look tomorrow when I have time.
> 
> By the way I haven't had much time to keep up with this project. Would you like to be added as an owner?

I'd be happy to help you out on maintaining this repo. I'm a typical user of yours but feel like I could give back some of the value you've given me. Thank you.

**Comment by ArcadeRenegade** [comment]
Thanks I invited you. Sorry for the late reply I've been so busy. I'm going to try and pull and merge this, this week but if you want to do it feel free to go ahead.

**Comment by ThaChillera** [comment]
> Thank you for this. This is really cool. I'll take a look tomorrow when I have time.
> 
> By the way I haven't had much time to keep up with this project. Would you like to be added as an owner?

Thanks but I have zero experience with C#, don't think that would be a great idea as long as you can still review/accept pull requests.

Will start work on the linux port soon(tm)

**Comment by ThaChillera** [comment]
So what is the status of this PR?

**Comment by ixuz** [comment]
I hope to review this PR soon. Sorry for the wait...

**Comment by ixuz** [comment]
Sorry for the long wait, but I've recently tried to get this port running but struggled with errors regarding duplicated assemblies.
@ThaChillera would you like to bring this PR up-to-date once again? There's a couple of merge conflicts.

**Comment by ThaChillera** [comment]
> Sorry for the long wait, but I've recently tried to get this port running but struggled with errors regarding duplicated assemblies.
> @ThaChillera would you like to bring this PR up-to-date once again? There's a couple of merge conflicts.

I will, currently busy though so I won't start work immediately

**Comment by ArcadeRenegade** [comment]
I'm really sorry I dropped the ball on this PR.

I am now in the middle of upgrading the repository to .NET 6 though. It's a big upgrade going from .NET 4.7.2 to .NET 6 😆

**Pull request closed without merging**
